using ChitChat.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChitChat.Models
{
    public class Contact
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string? AppUserId { get; set; }
        //the registered user that made this contact.

        [Required]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} and a Max {1} charactors", MinimumLength = 2)]
        [Display(Name = "First Name")]
        public string? FirstName { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} and a Max {1} charactors", MinimumLength = 2)]
        [Display(Name = "Last Name")]
        public string? LastName { get; set; }

        [NotMapped]
        public string? FullName { get { return $"{FirstName} {LastName}"; } }


        [Display(Name = "Birth Day")]
        [DataType(DataType.Date)]
        public DateTime? BirthDate { get; set; }
        //make when you generate this table that the correct date type is represented in the database

        [Required]
        [Display(Name = "Address")]
        public string? Address1 { get; set; }

        [Display(Name = "Address")]
        public string? Address2 { get; set; }

        [Required]
        public string? City { get; set; }

        [Required]
        [Display(Name = "Province")]
        public States State { get; set; }
        //My data type is now states to reference the enum we created.

        [Required]
        [Display(Name = "Postal Code")]
        [DataType(DataType.PostalCode)]
        public int ZipCode { get; set; }

        [Required]
        [EmailAddress]
        public string? Email { get; set; }


        [Required]
        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        public string? PhoneNumber { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime Created { get; set; }

        //Image properties
        public byte[]? ImageData { get; set; }
        public string? ImageType { get; set; }
        [NotMapped]
        public IFormFile? ImageFile { get; set; }
        //This is used to upload the image, supports image uploads


        //Virtuals (fk's)
        public virtual AppUser? AppUser { get; set; }
        //this is the one to the as.net users table
        public virtual ICollection<Category> Categories { get; set; } = new HashSet<Category>();
        //this goes to our join table. Which will be auto generated by ef core
        //There can be a bunch of categories that this contact is in. 1 contact to many categories.
    }
}
